include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_print: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_this: true
    unnecessary_new: true
    unnecessary_const: true
    unnecessary_string_interpolations: true
    prefer_interpolation_to_compose_strings: true
    avoid_redundant_argument_values: true
    always_declare_return_types: true
    annotate_overrides: true
    prefer_relative_imports: true
