targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          generate_connect_constructor: false
          scoped_dart_components: true
